name: "driftctl-action"
author: "Snyk"
description: "Run driftctl in your GitHub Actions workflow."

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  version:
    description: "The version of driftctl to install."
    required: false
    default: "latest"
  args: 
    description: 'Additional args to supply to scan'
    required: false
    default: ""

branding:
  icon: "cloud"
  color: "blue"
